# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dki.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_f_dki(object):
    def setupUi(self, f_dki):
        f_dki.setObjectName("f_dki")
        f_dki.resize(435, 457)
        self.txt_tenkh = QtWidgets.QLineEdit(f_dki)
        self.txt_tenkh.setGeometry(QtCore.QRect(160, 50, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_tenkh.setFont(font)
        self.txt_tenkh.setObjectName("txt_tenkh")
        self.txt_emailkh = QtWidgets.QLineEdit(f_dki)
        self.txt_emailkh.setGeometry(QtCore.QRect(160, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_emailkh.setFont(font)
        self.txt_emailkh.setObjectName("txt_emailkh")
        self.txt_sdtkh = QtWidgets.QLineEdit(f_dki)
        self.txt_sdtkh.setGeometry(QtCore.QRect(160, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_sdtkh.setFont(font)
        self.txt_sdtkh.setObjectName("txt_sdtkh")
        self.txt_dckh = QtWidgets.QLineEdit(f_dki)
        self.txt_dckh.setGeometry(QtCore.QRect(160, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_dckh.setFont(font)
        self.txt_dckh.setObjectName("txt_dckh")
        self.txt_uname = QtWidgets.QLineEdit(f_dki)
        self.txt_uname.setGeometry(QtCore.QRect(160, 250, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_uname.setFont(font)
        self.txt_uname.setObjectName("txt_uname")
        self.txt_pass = QtWidgets.QLineEdit(f_dki)
        self.txt_pass.setGeometry(QtCore.QRect(160, 300, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_pass.setFont(font)
        self.txt_pass.setObjectName("txt_pass")
        self.label = QtWidgets.QLabel(f_dki)
        self.label.setGeometry(QtCore.QRect(30, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(f_dki)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(f_dki)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(f_dki)
        self.label_4.setGeometry(QtCore.QRect(30, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(f_dki)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(f_dki)
        self.label_6.setGeometry(QtCore.QRect(30, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_dk = QtWidgets.QPushButton(f_dki)
        self.btn_dk.setGeometry(QtCore.QRect(270, 350, 93, 28))
        self.btn_dk.setObjectName("btn_dk")

        self.retranslateUi(f_dki)
        QtCore.QMetaObject.connectSlotsByName(f_dki)

    def retranslateUi(self, f_dki):
        _translate = QtCore.QCoreApplication.translate
        f_dki.setWindowTitle(_translate("f_dki", "Form"))
        self.label.setText(_translate("f_dki", "Họ và Tên"))
        self.label_2.setText(_translate("f_dki", "Email"))
        self.label_3.setText(_translate("f_dki", "SĐT"))
        self.label_4.setText(_translate("f_dki", "Địa chỉ"))
        self.label_5.setText(_translate("f_dki", "Tên đăng nhập"))
        self.label_6.setText(_translate("f_dki", "Mật khẩu"))
        self.btn_dk.setText(_translate("f_dki", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    f_dki = QtWidgets.QWidget()
    ui = Ui_f_dki()
    ui.setupUi(f_dki)
    f_dki.show()
    sys.exit(app.exec_())
