# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_tk = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_tk.setGeometry(QtCore.QRect(310, 100, 291, 31))
        self.txt_tk.setObjectName("txt_tk")
        self.txt_mk = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_mk.setGeometry(QtCore.QRect(310, 170, 291, 31))
        self.txt_mk.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_mk.setObjectName("txt_mk")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(510, 240, 93, 28))
        self.btn_login.setObjectName("btn_login")
        self.btn_dky = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dky.setGeometry(QtCore.QRect(310, 240, 93, 28))
        self.btn_dky.setObjectName("btn_dky")
        self.r_nv = QtWidgets.QRadioButton(self.centralwidget)
        self.r_nv.setGeometry(QtCore.QRect(310, 210, 95, 20))
        self.r_nv.setObjectName("r_nv")
        self.r_kh = QtWidgets.QRadioButton(self.centralwidget)
        self.r_kh.setGeometry(QtCore.QRect(420, 210, 95, 20))
        self.r_kh.setObjectName("r_kh")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tài khoản"))
        self.label_2.setText(_translate("MainWindow", "Mật khẩu"))
        self.btn_login.setText(_translate("MainWindow", "Đăng nhập"))
        self.btn_dky.setText(_translate("MainWindow", "Đăng ký"))
        self.r_nv.setText(_translate("MainWindow", "Nhân viên"))
        self.r_kh.setText(_translate("MainWindow", "Khách hàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
